### PR TITLE
Upgrading slf4j version

### PR DESCRIPTION
**Pull request by ranjithkumarshetty**
@ben-tsai Trying out more updated `slf4jVersion`

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by joejoe321321** [comment]
OK

**Comment by geekybaiyi** [comment]
hi @ranjithkumarshetty ,  is there anything in 1.7.20 you need that's not available in 1.7.12 ?

**Comment by joejoe321321** [comment]
BTW, can you illustrate why it is needed?

**Comment by ranjithkumarshetty** [comment]
Hi @joejoe321321  , I was hoping this would resolve the dependent project build issue ( also, upgrading would keep it close to most stable library ), but it did not solve it - hence closing the PR

**Pull request closed without merging**
